version: '3.7'

services:
  pay-mysql:
    container_name: pay-mysql
    image: mysql:5.7
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    environment:
      TZ: Asia/Seoul
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - pay-mysql-data:/var/lib/pay-mysql
volumes:
  pay-mysql-data:
