# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI(SDK)

on:
  push:
    paths:
      - libraries/pickk-pay-sdk/**

jobs:
  build-sdk:
    name: CI(SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libraries/pickk-pay-sdk

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install project dependencies (global)
        run: |
          cd ..
          npm install

      - name: Install project dependencies
        if: |
          steps.npm-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint check
        run: npm run lint

      - name: Unit Test & Make coverage
        run: npm run test
