name: Upload to S3 (server)

on:
  push:
    tags:
      - pickk-pay-server@*

jobs:
  deploy:
    name: Upload (server)
    runs-on: ubuntu-18.04
    environment: production
    defaults:
      run:
        working-directory: ./services/pickk-pay-server

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Move directory
        run: cd services/pickk-pay-server

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install project dependencies
        if: |
          steps.npm-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Set env
        run: cp .env.prod .env

      - name: Build
        run: npm run build

      - name: Zip Artifacts
        run: zip pickk-pay-server.zip -r . -x './.github/*' -x './test/*' -x './.git/*' -x './node_modules/*'

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./pickk-pay-server.zip s3://pickk-pay-server-zip
